In [1]:
import numpy as np

In [14]:
# Load data from .npy file
data = np.load('./data/training/trainMSGyroscope.npy')
numberOfActivities = data.shape[0]

# Inspect properties
print(f"Shape: {data.shape}")
print(f"Data type: {data.dtype}")
print(f"First 5 elements: {data[:5]}")

Shape: (2284, 268, 3)
Data type: float32
First 5 elements: [[[ 1.55487812e+00  2.80487823e+00  2.50000000e+00]
  [ 1.58536589e+00  2.83536601e+00  2.59146357e+00]
  [ 1.73780489e+00  3.07926846e+00  2.46951222e+00]
  ...
  [ 5.61280518e+01 -3.99390244e+00  1.49695129e+01]
  [ 4.80182953e+01 -7.40853691e+00  3.09451218e+01]
  [ 3.96341476e+01 -9.54268360e+00  4.79878044e+01]]

 [[ 7.01219559e-01  1.15853667e+00 -1.06707323e+00]
  [ 1.00609756e+00  1.28048778e+00 -1.43292689e+00]
  [ 9.45122004e-01  1.31097567e+00 -1.49390244e+00]
  ...
  [ 3.53658562e+01  2.61280499e+01  1.17926834e+02]
  [ 2.72865868e+01  2.63109760e+01  1.16554878e+02]
  [ 8.53658581e+00  2.63109760e+01  1.13262199e+02]]

 [[ 8.84146333e-01  5.48780501e-01  3.04878056e-02]
  [ 9.14634168e-01  7.62195110e-01 -3.04878056e-02]
  [ 9.45122004e-01  7.92682946e-01 -3.04878056e-02]
  ...
  [-2.32317085e+01  4.23780489e+00 -3.90243912e+00]
  [-4.93902445e+00  5.70121956e+00  7.31707335e-01]
  [ 2.24390259e+01  9.66463470e+00 

In [11]:
def mapCodeToActivity(activityCode):
    """
    Maps activity codes to their corresponding activity names.
    """
    activity_map = {
        0: "Bring",
        1: "Clean Floor",
        2: "Clean Surface",
        3: "Close Big Box",
        4: "Close Door",
        5: "Close Drawer",
        6: "Close Lid By Rotate",
        7: "Close Other Lid",
        8: "Close Small Box",
        9: "Close Tap Water",
        10: "Drink",
        11: "Dry Off Hands",
        12: "Dry Off Hands By Shake",
        13: "Eat Small",
        14: "Gargle",
        15: "Getting Up",
        16: "Hang",
        17: "Lying Down",
        18: "Open Bag",
        19: "Open Big Box",
        20: "Open Door",
        21: "Open Drawer",
        22: "Open Lid By Rotate",
        23: "Open Other Lid",
        24: "Open Small Box",
        25: "Open Tap Water",
        26: "Plug In",
        27: "Press By Grasp",
        28: "Press From Top",
        29: "Press Switch",
        30: "Put From Bottle",
        31: "Put From Tap Water",
        32: "Put High Position",
        33: "Put On Floor",
        34: "Read",
        35: "Rotate",
        36: "Rub Hands",
        37: "Scoop And Put",
        38: "Sitting Down",
        39: "Squatting Down",
        40: "Standing Up",
        41: "Stand Up From Squatting",
        42: "Take From Floor",
        43: "Take From High Position",
        44: "Take Off Jacket",
        45: "Take Out",
        46: "Talk By Telephone",
        47: "Throw Out",
        48: "Throw Out Water",
        49: "Touch Smartphone Screen",
        50: "Type",
        51: "Unhang",
        52: "Unplug",
        53: "Wear Jacket",
        54: "Write"
    }
    
    return activity_map.get(activityCode, "Unknown Activity")